eureka:
  client:
    register-with-eureka: false

server:
  port: 8666

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: http://localhost:8061
          predicates:
            - Path=/student/v1/api/**
        - id: schools
          uri: http://localhost:8062
          predicates:
            - Path=/school/v1/api/**