eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8040/eureka

server:
  port: 8061

spring:
  application:
    name: students
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/student
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect